new1

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -88,7 +88,15 @@ jobs:
          
       - name: Stop and remove container if running
         run: |
-         docker ps -q --filter "name=cnncls" | grep -q . && docker stop cnncls && docker rm -fv cnncls
+         echo "Checking if container cnncls exists..."
+         docker ps -q --filter "name=cnncls" | grep -q . && echo "Container cnncls found" || echo "Container cnncls not found"
+    
+         echo "Stopping container cnncls..."
+         docker stop cnncls
+    
+         echo "Removing container cnncls..."
+         docker rm -fv cnncls
+
        
       - name: Run Docker Image to serve users
         run: |
